### PR TITLE
Polish header

### PR DESCRIPTION
**Pull request by donokuda**
Using a much more higher rez Abbot head

> image

### CODE REVIEW

**Review by dahlbyk — COMMENTED** [review]
Did you forget to commit a change to `_appLogoPath`?
https://github.com/aseriousbiz/abbot-docs-new/blob/01b9ed713dd23941072d29c475c9b468bfdab652/src/docfx.json#L42

**Comment by donokuda** [comment]
yes.

**Comment by dahlbyk** [comment]
Conflicts!

**Review by dahlbyk — APPROVED** [review]
Feels like too much left margin on mobile, but desktop looks good.

**Comment by donokuda** [comment]
> Feels like too much left margin on mobile, but desktop looks good.

Oops. Good catch. Fixed in [`5b232a6`](https://github.com/aseriousbiz/abbot-docs-new/pull/26/commits/5b232a667cd5fb0908c186c2dba044d4e10ca6e8)

**Review by dahlbyk — APPROVED** [review]

**Pull request merged**
